changelog:
  exclude:
    labels:
      - prod-version
      - dev-version

  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking
    - title: New Features 🎉
      labels:
        - feature
    - title: Improvements 🚀
      labels:
        - enhancement
        - documentation
        - CI/CD
        - bugfix
    - title: Other Changes
      labels:
        - "*"
