name: Build package
description: Builds the package and check distribution files

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        python -m pip install $(grep build requirements_dev.txt | xargs)
        python -m pip install $(grep twine requirements_dev.txt | xargs)
      shell: bash

    - name: Build project and create distribution files
      run: python -m build
      shell: bash

    - name: Check distribution files with twine
      run: python -m twine check dist/*
      shell: bash
