name: Build package

runs:
  using: composite
  steps:
    - name: Build project and create distribution files
      run: python -m build
      shell: bash

    - name: Check distribution files with twine
      run: twine check dist/*
      shell: bash
