name: Build package

on:
  push:
    branches:
      - "main"
      - "dev/[0-9]*.[0-9]*.[0-9]*"
  pull_request:
    branches:
      - "main"
      - "dev/[0-9]*.[0-9]*.[0-9]*"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Build package
        uses: ./.github/actions/build_package
