name: Code Coverage [CodeCov]

on:
  push:
    branches:
      - "main"
      - "dev/*.*.*"
  pull_request:
    branches:
      - "main"
      - "dev/*.*.*"
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python "3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            config/requirements_dev.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r config/requirements_dev.txt
          pip install .

      - name: Test with coverage
        run: |
          coverage run -m pytest

      - name: Report coverage
        run: |
          coverage report

      - name: Upload coverage reports to Codecov
        run: |
          echo "Using codecov version: $(codecov --version)"
          codecov --verbose
