name: Code Coverage [CodeCov]

on:
  push:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r config/requirements_dev.txt

      - name: Test with coverage
        run: |
          coverage run -m pytest

      - name: Report coverage
        run: |
          coverage report

      - name: Upload coverage reports to Codecov
        run: |
          echo "Using codecov version: $(codecov --version)"
          codecov --verbose
