name: Create development branch

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "Release type"
        options:
          - major
          - minor
          - patch
        default: patch

permissions:
  contents: write

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python "3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            config/requirements_dev.txt

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install $(grep bump2version config/requirements_dev.txt | xargs)

      - name: Configure git
        run: |
          git config --global user.name "Github Actions BumpVersion"
          git config --global user.email "username@users.noreply.github.com"

      - name: Create new development branch
        run: |
          NEW_VERSION=$(bump2version ${{ github.event.inputs.release_type }} --dry-run --verbose 2>&1 | grep 'New version will be' | sed -r 's/.* will be '\''//;s/'\''$//;s/-dev[0-9]*$//')
          DEV_BRANCH_NAME="dev/${NEW_VERSION}"

          if [ -n "$(git branch --list $DEV_BRANCH_NAME)" ]
          then
            echo "Development branch for this version with name $DEV_BRANCH_NAME already exists."
            exit 1
          fi

          echo "Creating new development branch: $DEV_BRANCH_NAME"
          git checkout -b $DEV_BRANCH_NAME

          bump2version ${{ github.event.inputs.release_type }} --verbose
          git push origin $DEV_BRANCH_NAME --follow-tags
