name: Development Release

on:
  push:
    branches:
      - "dev/[0-9]*.[0-9]*.[0-9]*"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    if: github.actor != 'bump2version-gha[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

        # 3.0.1-dev2 -> 3.0.1-dev3 with build
      - name: Update development version
        uses: ./.github/actions/bump_version
        with:
          type: "build"
          commit: false
          tag: false
          push: false

      - name: Build package
        uses: ./.github/actions/build_package

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: dev-package-dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.actor != 'bump2version-gha[bot]'

    environment:
      name: testpypi
      url: https://test.pypi.org/p/soupsavvy

    env:
      GIT_TOKEN: ${{ secrets.GH_TOKEN }}

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dev-package-dist
          path: dist/

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Update development version with commit and tag
        uses: ./.github/actions/bump_version
        with:
          type: "build"
          commit: true
          tag: true
          push: true
