name: Deployment [test PyPI]

on:
  push:
    branches:
      - "main"

jobs:
  bump:
    name: Bump version 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this fetches all history
          fetch-tags: true # this fetches all tags
          token: ${{ secrets.GH_TOKEN }} # token for pushing to protected branch

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      # 3.0.1-dev5 -> 3.0.1-dev6 with build
      - name: Update development version
        uses: ./.github/actions/bump_version
        with:
          type: "build"
          commit: true
          tag: true
          push: true

  build:
    name: Build dev distribution 📦
    needs: bump
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # checkout at latest commit from previous job
          fetch-depth: 0

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Build package
        uses: ./.github/actions/build_package

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: dev-package-dist
          path: dist/

  publish:
    name: Publish distribution 📦 to Test PyPI
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/soupsavvy

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dev-package-dist
          path: dist/

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
