name: Documentation [Github Pages]

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  BRANCH_NAME: gh-pages
  BUILD_FOLDER: build_/

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # gh-pages is protected branch
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r docs/requirements.txt
          pip install -e .

      - name: Update index.rst
        run: |
          python docs/source/update_index.py

          if [ "$(git status --porcelain)" ]; then
            git add docs/source/index.rst
            git commit -m "Update index.rst [skip ci]"
            git push
          else
            echo "No update needed for docs/source/index.rst"
          fi

      - name: Sphinx build rst files
        run: |
          sphinx-apidoc -o docs/source soupsavvy --separate --force

      - name: Transform rst files
        working-directory: docs/source
        run: python renaming.py

      - name: Build HTML documentation
        run: |
          rm -rf ${BUILD_FOLDER}
          sphinx-build docs/source ${BUILD_FOLDER}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ env.BUILD_FOLDER }}
          force_orphan: true
