name: Deploy Documentation

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  BRANCH_NAME: gh-pages
  OUTPUT: docs/build/html/

jobs:
  build:
    name: Build Documentation 📚
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }} # token for pushing to protected branch

      - name: Output branch name
        run: |
          echo "Running workflow on branch ${GITHUB_REF_NAME}"
          echo "Current branch is `git branch --show-current`"

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install -r docs/requirements.txt

      - name: Make docs with Sphinx
        run: |
          bash docs/sphinx_run.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ${{ env.OUTPUT }}

  deploy:
    name: Deploy Documentation 🚀
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: Clean root directory
        run: |
          # we want to rewrite the root directory
          git rm -rf .

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: html-docs
          # download to root directory
          path: .

      - name: Commit and Push to gh-pages
        run: |
          git config --global user.name "gh-pages[bot]"
          git config --global user.email "username@users.noreply.github.com"

          # add .nojekyll to allow serving of files starting with an underscore
          touch .nojekyll

          echo "Committing and pushing..."
          git add .
          git commit -m "Update documentation"
          git push origin ${{ env.BRANCH_NAME }}
