name: Documentation [Github Pages]

on: [push]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r docs/requirements.txt
          pip install .

      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs/source soupsavvy --separate --force
          rm -rf _build
          sphinx-build docs/source build_

      - name: Push to gh-pages
        run: |
          # Check if the gh-pages branch exists
          if [ `git branch --list $branch_name` ]; then
              echo "Switching to $(branch_name) branch"
              git checkout $(branch_name)
              # Remove all files and directories in the branch
              git rm -rf .
          else
              echo "Creating $(branch_name) branch"
              git checkout --orphan $(branch_name)
              git reset --hard
          fi

          # Add build_ directory and commit changes
          cp -r build_/* .
          git add .
          git commit -m "Update documentation"
          git push origin $(branch_name)
