on:
  push:
    branches:
      # for testing
      - cd/auto_release

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this fetches all history and tags

      - name: Get interested tags
        run: |
          git checkout main
          tag=$(git describe)
          echo "Release tag: $tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          draft: false
          prerelease: false
