name: Linting

on:
  push:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install $(grep flake8 config/requirements_dev.txt | xargs)

      - name: Lint with flake8
        run: |
          python -m flake8 --config tox.ini
