name: Prevent Boring Release PR

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
    branches:
      - "main"

jobs:
  check_no_meme:
    runs-on: ubuntu-latest
    steps:
      - name: Check for no meme label
        id: check_label
        run: |
          forbidden_label="no meme"

          # Get the pull request labels using jq and store it in a variable
          pr_labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          # Check if 'no meme' label exists in the pull request labels
          if echo "$pr_labels" | grep -q "$forbidden_label"; then
            echo "Error: MEME POLICE! No way it's getting released, add some meme, stay sane and keep troops entertained"
            exit 1
          fi
