name: Deployment [PyPI]

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

        # 3.0.1-dev5 -> 3.0.1 with release
      - name: Update development version
        uses: ./.github/actions/bump_version
        with:
          type: "release"
          commit: false
          tag: false
          push: false

      - name: Build package
        uses: ./.github/actions/build_package

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: prod-package-dist
          path: dist/

  publish_prod:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/soupsavvy

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: prod-package-dist
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Update development version with commit and tag
        uses: ./.github/actions/bump_version
        with:
          type: "release"
          commit: true
          tag: true
          push: true

  publish_dev:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true

    environment:
      name: testpypi
      url: https://test.pypi.org/p/soupsavvy

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: prod-package-dist
          path: dist/

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  github_release:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this fetches all history and
          token: ${{ secrets.GH_TOKEN }}

      - name: Get interested tags
        run: |
          git checkout main
          tag=$(git describe)
          echo "Release tag: $tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ env.tag }}
          name: ${{ env.tag }}
