
name: Run Demos

on:
    push:
      branches:
        - "main"
        - "dev/[0-9]+.[0-9]+.[0-9]+"
    pull_request:
      branches:
        - "main"
        - "dev/[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch: {}

permissions:
  contents: read

jobs:
  tests:
    continue-on-error: true

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python and Upgrade pip
      uses: ./.github/actions/setup_python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements_dev.txt
        python -m pip install pytest-custom_exit_code
        python -m pip install .

    - name: Test with pytest
      run: |
        python -m pytest --nbmake -v demos/
