name: Tests - Standard

on:
  push:
    branches:
      - "main"
      - "dev/[0-9]*.[0-9]*.[0-9]*"
  pull_request:
    branches:
      - "main"
      - "dev/[0-9]*.[0-9]*.[0-9]*"
  workflow_dispatch: {}

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r config/requirements_dev.txt
          pip install .

      - name: Test with pytest
        run: pytest -v -ra
