name: Unit Tests

on:
  push:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "dev/[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

jobs:
  tests:
    continue-on-error: true

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Upgrade pip
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r config/requirements_dev.txt

      - name: Test with pytest
        run: |
          python -m pytest -v -ra
